### ISSUE TITLE
Provide some cli options

### ISSUE THREAD

**Issue by matthewp** [google/schism#30]
Currently it takes an input scheme file and dumps to `out.wasm`. It would be nice if there were some standard cli options like `-o, --out`, `--help`, and `--version`.

Also, as a default I think it's typical to name binaries after the input file, so if `example.ss` is the entry module then `example.wasm` would be produced. Also I think some compiles do default to `out` so maybe this shouldn't change.

**Comment by matthewp** [comment]
I'm willing to take this on if you will accept a PR.

**Comment by eholk** [comment]
I'd be happy to take a PR! All of those options sound like great additions.

I went with `out.wasm` to sort of follow gcc's default name of `a.out`, but I agree that `example.ss` to `example.wasm` is better.

**Comment by eholk** [comment]
If you haven't already done it, you'll need to sign a CLA before I can accept the PR. You can do that here: https://cla.developers.google.com/clas

There's a bot that runs on the PR that will check and remind you if you still need to do it.

**Comment by matthewp** [comment]
I'm a little conflicted between leaving it as `out.wasm` or changing to `<filename>.wasm`. Do you have a strong preference? If not I might just leave it as is for now.

**Comment by eholk** [comment]
I don't have a strong preference.

In the absence of strong preferences, I'd maybe leave it as is for now, since otherwise the test runner will need more changes to find the right output file.

In the longer term, I'd like to support library loading and have the output filename match whatever the library system expects. So, a library name like `(schism compiler optimizer)` would go in something like `lib/schism/compiler/optimizer.wasm`.
